### ISSUE TITLE
Redraw images (.png) in high quality

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#14]
Currently, the https://openweathermap.org/ returns images which are very poor quality. The plan is to download all possible images of weather from their server, and make high quality replicas.

**Comment by fenadegil2013** [comment]
I want to do this task, can you assign it to me please.

**Comment by ardovic** [comment]
Sure, I was unable to assign you here on GitHub, since you don't appear on the assignee list for some reason, but consider yourself assigned. For now, please put all of the images you have inside "drawable" folder and make a pull request.

**Comment by fenadegil2013** [comment]
Okay, I'll do it when ready, already forked the project.

**Comment by ardovic** [comment]
Issue still open. Seems that @PaanwalaAhuja91 didn't complete this task.

**Comment by kajal1811** [comment]
Does these images still require to be drawn in high quality? If yes, I can work on it.

**Comment by unnati914** [comment]
even i want to work

**Comment by ardovic** [comment]
@unnati914 you're welcome!

**Comment by ardovic** [comment]
@kajal1811 you too!

**Comment by unnati914** [comment]
thank you so much!

**Comment by kajal1811** [comment]
Thank you!
