### ISSUE TITLE
Add navigation drawer 

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#17]
A simple navigation drawer for future functionality. Currently, we plan to add authentication, profile (name-email-avatar) for preferences saving, forecast types, credits, notification options and general customization settings buttons. 

P.S.: The list of functionality is not the part this issue.

**Comment by BrahM0s** [comment]
I would like to work on this issue. Please assign me to it.

**Comment by ardovic** [comment]
You don't appear in the list for assignees at the moment. Consider yourself being assigned.

Looking forward for your solution in apull request soon. If you never did a pull request before, makesure to read the README.md file of the project.

**Comment by BrahM0s** [comment]
I'm pretty much done except for this one GLARING error.
It says - Cannot resolve symbol 'R'
I've gone through all the forums but none of their suggestions helped.
Do you have any idea on how to approach this?

**Comment by ardovic** [comment]
It might be because you didn't install the Lombok plugin. Follow instructions here: https://projectlombok.org/setup/android

**Comment by ardovic** [comment]
Can you commit your changes and push them to your fork, I'll take a look.

**Comment by BrahM0s** [comment]
Was unable to commit but I have uploaded the changed files here;
https://github.com/BrahM0s/Weather-App-with-Nav
Please have a look and let me know where I have gone wrong.

**Comment by BrahM0s** [comment]
I screwed up the merge so please check the link provided and not the fork.

**Comment by BrahM0s** [comment]
Hey! It took a while but I fixed it. I was able to put in the navigation drawer. 
Unfortunately, very stupidly I deleted the fork. How do I make a pull request now?
Here's the link to the final fix:
https://github.com/BrahM0s/Open-Weather-Android

**Comment by ardovic** [comment]
Hi, unfortunately the only way to make a pull request is to have a fork of the original project. You'll have to make another fork and copy/paste your changes from your current project, then make a pull request as usual.

**Comment by BrahM0s** [comment]
Made the pull request. Do check.

**Comment by ardovic** [comment]
Great. I merged it to current project. Very nice job! Since you're a contributor, I invite you to our Android OSC (Open Source Community) organisation as a member. please accept at: https://github.com/android-osc

**Comment by ardovic** [comment]
Regarding the navigation drawer. It's good, but next we need to bring it forward (above the toolbar). Also, an icon should be added to the left side of the toolbar, so that it can be used as a button to open navigation drawer. Take a look at this example:

![layout_structure_appbar_structure4](https://user-images.githubusercontent.com/30338343/39859140-759e272c-5441-11e8-8a0d-3c8371edcd17.png)

**Comment by BrahM0s** [comment]
Hey sorry for going AWOL. I was on a long weekend. I'm just about done with the necessary changes. You can expect a pull request soon.

**Comment by nsvrohit** [comment]
Fixed that issue. Please check the pull request.

**Comment by kapilajayant** [comment]
> A simple navigation drawer for future functionality. Currently, we plan to add authentication, profile (name-email-avatar) for preferences saving, forecast types, credits, notification options and general customization settings buttons.
> 
> P.S.: The list of functionality is not the part this issue.

Hi, I think there is plenty much more work to do on the nav bar as it is not working. I cloned the dev branch and ran it on my device, what I saw was that the action bar is overlapping the nav bar and the contents of nav bar are not accessible. 
I would like to work on that issue.

**Comment by ardovic** [comment]
@kapilajayant Hi Jayant! I'm very glad you came along. Indeed, you can start working on the issue, it would be superb if you'd find out and solve the NavDrawer issue. If you need help let me know, I really really want to restart active work on this project and make it more beginner-friendly and useful.

**Comment by kapilajayant** [comment]
Ok, I'll start working on it. Can you help me find the latest build of the app so that I can see all the latest updates? Also, i was not able to open the project when I cloned the master branch. what's up with that?

**Comment by ardovic** [comment]
@kapilajayant I just downloaded the project and ran it from scratch, everything seems to work just fine.

**Comment by ardovic** [comment]
@kapilajayant I have updated dependencies and migrated to Android X, please pull changes to your project ASAP, so that it works and will merge in the future without conflicts.

**Comment by kapilajayant** [comment]
Ok I'll start fixing the navigation bar and action bar issue
