### ISSUE TITLE
Credits "Activity" required

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#20]
We need a nice easy-to-update Activity with credits list, where everyone who had contributed to the project will be listed. 

This activity will be accessed from navigation menu.

At first, the list will be manually edited. Later we should connect it to projects github API (it should be possible), this way the list will be updated each time a new contributor appears.

**Comment by yskwon1231** [comment]
I'd like to work on this issue if it is okay.  Can I work on it?

**Comment by ardovic** [comment]
Hi, yes of course. I was unable to assign you here on GitHub, because your name didn't appear in the list, but it is normal, consider yourself assigned onto this issue. 

If you get stuck, feel free to ask here at any time. Good luck!

**Comment by yskwon1231** [comment]
I've been working on this issue by making fragments that appear when items in navigation menu are clicked.  But  items in navigation menu does not react to the click.  
I can't find a way to solve this problem. Can somebody give me some help?

**Comment by ardovic** [comment]
please make a commit into your fork and make request to **dev branch** of the original project with recent changes and write here, I'll check and see what's the problem.

**Comment by ardovic** [comment]
Your changes have been added to the project successfully! Since you've contributed to the project, you've gained the right of being a member of Android OSC (Open Source Community) - check your invitation here: https://github.com/android-osc.

Important: If you want to make the badge on your profile page visible by others, make sure to change your "Membership" status to "Public"

**Comment by rajBopche** [comment]
Please close this issue if resolved @ardovic  @yskwon1231
