### ISSUE TITLE
Icon Proposal 

### ISSUE THREAD

**Issue by mendezand** [ardovic/Open-Source-Android-Weather-App#28]
Hi.
I have created an icon for the project.
![image](https://user-images.githubusercontent.com/38763253/39823468-21e05ce8-537b-11e8-962c-4dcbf5fe2e30.png)

***

You can place BG and FG in [Adapticon](https://adapticon.tooo.io) to test it.

**FG** 
![artboard 1xxxhdpi](https://user-images.githubusercontent.com/38763253/39824055-6ccaa53c-537c-11e8-9169-1d77c27b4115.png)

**BG**
 ![artboard 2xxxhdpi](https://user-images.githubusercontent.com/38763253/39824061-71bec1cc-537c-11e8-8458-d201e46468d2.png)

***

You can ask for any modification. If everything is fine, I will proceed to send the editable and final files.

**Comment by mendezand** [comment]
My contribution has been designed for adaptive applications icons. The current logos seem to me they do not have a very attractive image. I can add the logos you have mentioned to me in the background of the icon logo.

**Comment by ardovic** [comment]
Sure, if you can design icons that have all 3 points I mentioned and it will be better than the current, we will use it. Your contribution will be counted anyways.

**Comment by mendezand** [comment]
I have made the logo much bigger to add the logos of OSI and Android.
![mesa de trabajo 1xxxhdpi](https://user-images.githubusercontent.com/38763253/39847644-9487d230-53d0-11e8-9fa8-5bb101000bf5.png)


Icons for devices using Play Store not put their logo because their size are small measures, however have an excellent adaptation for Android devices.

**Comment by ardovic** [comment]
Good, now you can make a circular version for android 7+. Also both versions of logos should be available in 1024, 512, 256, 192, 144, 96, 72 and 48 px sizes. After they are done make a fork, put your files in folders I've mentioned and make a pull request.

**Comment by mendezand** [comment]
I created the Pull Request. You can download the editable files, .PNG and .SVG [here](https://drive.google.com/open?id=1PG5ANeBK1EC-5ThGvGgEFPVXYHb5mvCp).

**Comment by ardovic** [comment]
Great, you've done good job!
