### ISSUE TITLE
Layout improvements required

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#3]
Current layout is terrible, we need some serious visual improvements.

**Comment by MauzerTheCat** [comment]
I can do it, but what way di you see it? I mean what should be shown on the main screen, what kind of data? Maybe, you have an example of the result you want to see?

**Comment by kapilajayant** [comment]
> Current layout is terrible, we need some serious visual improvements.

Hi, as this issue is still open, I would like to work on this issue as so far no changes have been made to the latest commit inside the dev branch. I am thinking of ways to improve the interface and the data on the main screen look more representative.

**Comment by ardovic** [comment]
@kapilajayant Jayant, great news you paid interest to the issue. If you have any ideas please share, we will think about how to improve the situation.

**Comment by kapilajayant** [comment]
I can change the layout of the results i.e. Rain, pressure, humidity, wind and make it look more representative. Can you assign me in this issue?

**Comment by ardovic** [comment]
@kapilajayant sure

**Comment by ardovic** [comment]
@kapilajayant If you insist, you can create a specific new issue, and I'll be able to assign you onto it.

**Comment by kapilajayant** [comment]
Ok

**Comment by kapilajayant** [comment]
I just committed my code and made a pull request. Do check.

**Comment by ardovic** [comment]
@kapilajayant great! Your changes passed tests and were merged into master. Congrats on your first contribution to our humble open source project!

**Comment by kapilajayant** [comment]
Glad to work on it. I think I can make it even better, shall i create a new issue and work on it?

**Comment by ardovic** [comment]
@kapilajayant I've updated your CardView dependencies to AndroidX, make sure to pull current master branch to your project. Sure, it's the correct procedure, where you open and Issue and I can assign you onto it!
