### ISSUE TITLE
Google Play feature graphic

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#31]
We need a feature graphic for Google Play. Size is 1024 width x 500 hight in pixels.  It should be related to weather. It should contain an Android Logo and [Open Source Logo](https://goo.gl/images/iYjD9u)

**Comment by mendezand** [comment]
Editable Files.
https://drive.google.com/file/d/1RqsWqbPIEXLVGudYEzQOiSnI3qfR64i4/view?usp=sharing

**Comment by ardovic** [comment]
Great, thank you for submitting them. They might be useful for future graphic designs related to our project!
