### ISSUE TITLE
Rename logo files and put them in appropriate folders w.r.t. Android guidelines

### ISSUE THREAD

**Issue by ardovic** [ardovic/Open-Source-Android-Weather-App#35]
BEGINNER ANDROID DEVELOPER TASK. Task is very simple and will teach you how to set a custom logo for an application. 

We have 2 folders in root [CircularLogo](https://github.com/ardovic/Open-Source-Android-Weather-App/tree/master/CircularLogo) and [LogoDesign](https://github.com/ardovic/Open-Source-Android-Weather-App/tree/master/LogoDesign) containing our application logos. 

Select the better looking set of icons (hint: they are more recent) and rename them as "ic-launcher" and overwrite them over the default android app logos inside mipmap* folders.

**Comment by MrCondescending** [comment]
I would like to be assigned to this issue. I believe I have fully completed this task already

**Comment by ardovic** [comment]
Hi, sure, consider yourself assigned! Waiting for your pull request with changes.
