### ISSUE TITLE
Adding important guideline documents

### ISSUE THREAD

**Issue by santoshhiremani** [ardovic/Open-Source-Android-Weather-App#42]
Hi,
May I contribute some interesting documentation for this project, like setup documentation, code of conduct, code contribution and Bug reports guidelines.

**Comment by ardovic** [comment]
Hi, of course, you are welcome to contribute and add documentation and other necessities. I've assigned you to this issue, feel free to make changes and send pull requests.

**Comment by santoshhiremani** [comment]
Thanks, I will do that soon
