### ISSUE TITLE
Logo Design Proposal

### ISSUE THREAD

**Issue by debpedrano** [ardovic/Open-Source-Android-Weather-App#44]
Greetings Project Owner, 

I am a graphics designer who contributes on any Open Source projects. I saw your project that is really helpful in the community, I am interested in making a NEW LOGO because the current logo is not properly constructed and it would be an honor to enhance it.

I am asking your permission to do it.

Regards,

Deb

**Comment by ardovic** [comment]
Hi, Deb

You are welcome to contribute and make a new logo for this project.
I'm assigning you to this issue and looking forward for your contributions.

With kindest regards,
Serj

**Comment by debpedrano** [comment]
@ardovic I do hope, I made it right :D 
![image](https://user-images.githubusercontent.com/40510200/47228281-6930f880-d3f7-11e8-9ece-ed849b598f41.png)

**Comment by debpedrano** [comment]
The first one or the second one @ardovic ?

**Comment by ardovic** [comment]
I'd prefer the first one better

**Comment by debpedrano** [comment]
I sent a PR

![banner](https://user-images.githubusercontent.com/40510200/47332242-492c5e00-d6b1-11e8-85a5-e901ee658f3a.png)

**Comment by debpedrano** [comment]
@ardovic 
Hello sir Serj, I sent a PR. If we have some changes, please tell me so that i can make some edits. Thank you
