### ISSUE TITLE
AppModule Class has some boiler plate code, replace its args constructor with @BindsInstance and @ComponentBuilder

### ISSUE THREAD

**Issue by rajBopche** [ardovic/Open-Source-Android-Weather-App#47]
Describe your issue here.
AppModule class in DI package has a parameterized constructor for capturing context and then immediately provides it. We can reduce that boilerplate code with help of @BindsInstance, @ComponentBuilder and  @Binds   annotation

### Would you like to work on the issue?
I would like to optimize this boilerplate code.

**Comment by ardovic** [comment]
You are welcome, consider yourself assigned.
