### ISSUE TITLE
Deprecated Dependency

### ISSUE THREAD

**Issue by jaspreetsidhu3** [ardovic/Open-Source-Android-Weather-App#54]
I just fork your project and And while understanding the workflow of your project I see deprecated dependency in build.gradle file.
I can update this dependency to **newer onces**.

### Would you like to work on the issue?
Yes, I beginner in contributing So, I love to solve this issue .

Waiting for owner/contributor response to work on this issue.

**Comment by ardovic** [comment]
Good idea, updating dependencies is crucial for the project state. Consider yourself assigned, you can start working on this issue immediately!
