### ISSUE TITLE
Want to add features

### ISSUE THREAD

**Issue by jaspreetsidhu3** [ardovic/Open-Source-Android-Weather-App#56]
**In activity_main.xml**

- There is no hint in AutoCompleteTextView

**_In NavigationView_ menu items on click its showing toast "Not implemented yet"**
The items where I can work
- Setting
- About us
- Share
- Privacy Policy

### Expected behaviour

- In autocompletetextview I can add hint as "Add Location" or whatever you suggest
- NavigationView items onClick I want your suggestion So that I can work according to it

### Would you like to work on the issue?
Yeah, why not😇

**Comment by ardovic** [comment]
Great work on yor previous contribution! Sure, you're welcome to create new screens (Setting, Share - rasiest, About us - where you can either hardcode list of contributers, or use Github API to load list of contributers - maybe after).

**Comment by Poornirt** [comment]
@ardovic Issue still open. I would like to work on navigation view menu if it isn't started yet.
