### ISSUE TITLE
Want to add user's current location feature

### ISSUE THREAD

**Issue by aakashmeht** [ardovic/Open-Source-Android-Weather-App#59]
### Description
In MainActivity.java, Using GPS provider and Network provider we can get the user's current location. When the user opens the app we can display weather details for that location. Anyway, the user can also search for other locations like currently they are doing.

### Steps to reproduce
If the user has given permission for the location, we can get the user's location by different providers like GPS provider, Network provider. We can use the background service to get the user's current location geographic coordinates(Latitude and Longitude). Then using the openweathermap API  we can get weather details for that coordinates.
E.g. api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={API key}

### Expected behaviour
We can utilize location in different ways like when the user opens an app, the app will display details for the user's current location.

### Actual behaviour
The app is displaying weather details of the last searched location.

### Would you like to work on the issue?
I would like to work on this If you want.

**Comment by ardovic** [comment]
Good idea and perfect description. Of course, I would be greatful if you implemented this issue!
