### ISSUE TITLE
About us in Navigation Menu Crash (If not connected to Internet)

### ISSUE THREAD

**Issue by Poornirt** [ardovic/Open-Source-Android-Weather-App#61]
Navigation Menu About us Crash (If not connected to network)

### Steps to reproduce
- Turn off your internet
- Click on About us in Navigation view
- Gets a crash 

### Expected behaviour
- If an application not connected to internet, do not start async task  and show a toast stating no internet connection

### Actual behaviour
- App crashes 

### Would you like to work on the issue?
Yes

**Comment by ardovic** [comment]
Great, looking forward for a pull request with the fix!
